apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service
subsets:
- addresses:
    - ip: 10.244.1.13
  ports:
    - port: 5432
