apiVersion: v1
kind: Pod
metadata:
  name: postgres-database
spec:
  containers:
  - name: postgres
    image: postgres:latest
    env:
    - name: POSTGRES_DB
      value: mydatabase
    - name: POSTGRES_USER
      value: user
    - name: POSTGRES_PASSWORD
      value: password
    ports:
    - containerPort: 5432
