apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: load-test
  name: load-test-service-linha-comando
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: load-test
  type: NodePort
status:
  loadBalancer: {}
