apiVersion: v1
kind: LimitRange
metadata:
  name: meus-limites
spec:
  limits:
  - type: Container # POD / PersistentVolumeClaim / Container
    default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "500m"
      memory: "500Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "50m"
      memory: "100Mi"
