apiVersion: v1
kind: Service
metadata:
  name: kubernetes-proxy
  namespace: default
spec:
  type: ExternalName
  externalName: kubernetes.io
  ports:
  - port: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: kubernetes.io
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: k8s.averaacademy
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-proxy
            port:
              number: 443