apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-demo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      