apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probes
  name: probes
spec:
  containers:
  - image: averaacademy/kubernetes:probes
    name: probes
    resources: {}
    startupProbe:
    # exec / httpGet / tcpSocket
      tcpSocket:
        port: 80
      initialDelaySeconds: 1
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /readiness
        port: 80
        httpHeaders:
        - name: "X-SLEEP-TIME"
          value: "0"
      initialDelaySeconds: 1
      periodSeconds: 5
      failureThreshold: 10
      successThreshold: 3
    env:
    - name: "FIRST-START"
      value: "0"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
