apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-estatico-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
      